tst

diff --git a/.github/workflows/setup_lakehouse.yml b/.github/workflows/setup_lakehouse.yml
--- a/.github/workflows/setup_lakehouse.yml
+++ b/.github/workflows/setup_lakehouse.yml
@@ -1,38 +1,72 @@
-# This is a basic workflow to help you get started with Actions
+name: 01. Strife - Setup Lakehouse
 
-name: Setup Lakehouse
+# Este arquivo de workflow do GitHub Actions é utilizado para configurar e implantar
+# um ambiente de Lakehouse no Azure utilizando Terraform. Ele é composto por quatro jobs principais:
+# 1. build: Faz o checkout de um repositório privado e faz o upload de artefatos necessários.
+# 2. setup-lakehouse: Configura o ambiente de Lakehouse utilizando Terraform.
+# 3. setup-unity-catalog: Configura o Unity Catalog no Azure Databricks utilizando Terraform.
+# 4. setup-adb-compute: Configura os recursos de computação do Azure Databricks utilizando Terraform.
+#
+# O workflow é acionado manualmente através da aba Actions no GitHub.
+# Ele utiliza runners do Ubuntu para executar os jobs e faz uso de variáveis de ambiente
+# e segredos armazenados no GitHub para autenticação e configuração.
 
-# Controls when the workflow will run
+# This GitHub Actions workflow file is used to set up and deploy
+# a Lakehouse environment on Azure using Terraform. It consists of four main jobs:
+# 1. build: Checks out a private repository and uploads necessary artifacts.
+# 2. setup-lakehouse: Sets up the Lakehouse environment using Terraform.
+# 3. setup-unity-catalog: Sets up the Unity Catalog on Azure Databricks using Terraform.
+# 4. setup-adb-compute: Sets up the Azure Databricks compute resources using Terraform.
+#
+# The workflow is triggered manually through the Actions tab on GitHub.
+# It uses Ubuntu runners to execute the jobs and utilizes environment variables
+# and secrets stored in GitHub for authentication and configuration.
+
+# Define quando o workflow será executado
+# Define when the workflow will be triggered
 on:
-  # Allows you to run this workflow manually from the Actions tab
+  # Permite executar este workflow manualmente a partir da aba Actions
+  # Allows this workflow to be triggered manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# Define os jobs que serão executados no workflow
+# Define the jobs that will be executed in the workflow
 jobs:
-  # This workflow contains a single job called "build"
+  # Primeiro job: build
+  # First job: build
   build:
     name: Strife Build
-    # The type of runner that the job will run on
+    # Define o tipo de runner que o job será executado
+    # Define the type of runner the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    # Define os passos que serão executados no job
+    # Define the steps that will be executed in the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      # Faz o checkout de outro repositório privado
+      # Check out another private repository
+      - name: Check out my other private repo
+        uses: actions/checkout@v4
+        with:
+          repository: lealdouglas/strife
 
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v1
+      # Faz o upload dos artefatos necessários
+      # Upload necessary artifacts
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v4
         with:
           name: lakehouse
-          path: ${{ github.workspace }}//azsetup/lakehouse
+          path: ${{ github.workspace }}/azsetup/lakehouse
 
-  deploy-dev-infra:
-    name: Strife Deploy infra-dev
+  # Job para configurar o ambiente de Lakehouse
+  # Job to set up the Lakehouse environment
+  strife-setup-lakehouse:
+    name: Strife Setup Lakehouse
     runs-on: ubuntu-latest
 
     defaults:
       run:
-        working-directory: ${{ github.workspace }}//azsetup/lakehouse
+        working-directory: ${{ github.workspace }}/azsetup/lakehouse
 
     env:
       ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
@@ -45,28 +79,64 @@ jobs:
 
     needs: build
     steps:
+      # Baixa o artefato do Terraform
+      # Download the Terraform artifact
       - name: Download Terraform
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4
         with:
           name: lakehouse
-          path: ${{ github.workspace }}//azsetup/lakehouse
+          path: ${{ github.workspace }}/azsetup/lakehouse
 
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install PyYAML
+        run: pip install pyyaml
+
+      - name: Check if YAML file exists
+        run: |
+          if [ ! -f "${{ github.workspace }}/strife_env/strife_config.yaml" ]; then
+            echo "YAML file not found!"
+            exit 1
+          fi
+
+      - name: Read YAML file
+        id: read_yaml
+        run: |
+          python -c "
+          import yaml
+          import os
+          with open('../../strife_env/strife_config.yaml', 'r') as stream:
+              config = yaml.safe_load(stream)
+              for key, value in config.items():
+                  print(f'::set-output name={key}::{value}')
+          "
+
+      - name: Set environment variables from YAML
+        run: |
+          echo "domain=${{ steps.read_yaml.outputs.domain }}" >> $GITHUB_ENV
+          echo "catalog=${{ steps.read_yaml.outputs.catalog }}" >> $GITHUB_ENV
+          echo "project=${{ steps.read_yaml.outputs.project }}" >> $GITHUB_ENV
+
+      # Configura e inicializa o Terraform
+      # Set up and initialize Terraform
       - uses: hashicorp/setup-terraform@v2
         with:
           terraform_wrapper: false
-
       - name: Terraform Init
-        id: init
         run: terraform init
 
+      # Valida a configuração do Terraform
+      # Validate the Terraform configuration
       - name: Terraform Validate
-        id: validate
         run: terraform validate -no-color
 
+      # Gera e aplica o plano de execução do Terraform
+      # Generate and apply the Terraform execution plan
       - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color -var "envv=${{vars.ENVV}}"
+        run: terraform plan -no-color -var "domain=${{env.domain}}" -var "catalog=${{env.catalog}}" -var "project=${{env.project}}"
         continue-on-error: true
-
       - name: Terraform Apply
-        run: terraform apply -auto-approve -var "envv=${{vars.ENVV}}"
+        run: terraform apply -auto-approve -var "domain=${{env.domain}}" -var "catalog=${{env.catalog}}" -var "project=${{env.project}}"
